/*
 * 交我导数据文件
 *
 * 日常维护只需要修改本文件，交我导.html 无需改动。
 * 网站格式：{name:"名称",cat:"分类",type:"website",url:"官网地址",desc:"说明"}
 * 公众号格式：{name:"微信内搜索名称",cat:"分类",type:"wechat",desc:"说明"}
 * 每一项之间保留英文逗号；文字和网址请放在英文双引号中。
 */
window.JIAOWODAO_META = {
  updatedAt:"2026-07-13"
};

window.JIAOWODAO_DATA = [
  // 常用门户与系统
  {name:"上海交通大学官网",cat:"综合门户",type:"website",url:"https://www.sjtu.edu.cn/",desc:"学校中文主页"},
  {name:"院系设置",cat:"综合门户",type:"website",url:"https://www.sjtu.edu.cn/yxsz/",desc:"学校官方院系名录"},
  {name:"机构设置",cat:"综合门户",type:"website",url:"https://www.sjtu.edu.cn/jgsz/",desc:"学校官方机构名录"},
  {name:"交我办",cat:"综合门户",type:"website",url:"http://my.sjtu.edu.cn/",desc:"网上办事与校园服务"},
  {name:"统一身份认证 JAccount",cat:"综合门户",type:"website",url:"https://jaccount.sjtu.edu.cn/",desc:"全校统一登录入口"},
  {name:"交大新闻网",cat:"综合门户",type:"website",url:"https://news.sjtu.edu.cn/",desc:"学校新闻与学术资讯"},
  {name:"教学信息服务网",cat:"综合门户",type:"website",url:"https://i.sjtu.edu.cn/",desc:"选课、成绩等教学服务"},
  {name:"交大邮箱",cat:"综合门户",type:"website",url:"https://webmail.sjtu.edu.cn/",desc:"师生邮箱系统"},
  {name:"图书馆",cat:"综合门户",type:"website",url:"https://www.lib.sjtu.edu.cn/",desc:"馆藏检索与电子资源"},
  {name:"网络信息中心",cat:"综合门户",type:"website",url:"https://net.sjtu.edu.cn/",desc:"校园网与信息化服务"},
  {name:"VPN 服务",cat:"综合门户",type:"website",url:"https://vpn.sjtu.edu.cn/",desc:"校外访问校内资源"},
  {name:"教师个人主页系统",cat:"综合门户",type:"website",url:"https://faculty.sjtu.edu.cn/",desc:"全校教师主页"},
  {name:"在线教学平台",cat:"综合门户",type:"website",url:"https://oc.sjtu.edu.cn/",desc:"课程与在线教学"},
  {name:"水源社区",cat:"综合门户",type:"website",url:"https://shuiyuan.sjtu.edu.cn/",desc:"校园社区"},
  {name:"交大地图",cat:"综合门户",type:"website",url:"http://map.sjtu.edu.cn/",desc:"校园地图与地点查询"},
  {name:"信息公开网",cat:"综合门户",type:"website",url:"http://gk.sjtu.edu.cn/",desc:"学校信息公开"},

  // 职能部门
  {name:"党政办公室",cat:"职能部门",type:"website",url:"http://dzb.sjtu.edu.cn/",desc:""},
  {name:"纪检监察机构",cat:"职能部门",type:"website",url:"http://jiwei.sjtu.edu.cn/",desc:""},
  {name:"党委组织部",cat:"职能部门",type:"website",url:"http://zzb.sjtu.edu.cn/",desc:""},
  {name:"党委宣传部",cat:"职能部门",type:"website",url:"https://dwxcb.sjtu.edu.cn/",desc:""},
  {name:"党委统战部",cat:"职能部门",type:"website",url:"http://tzb.sjtu.edu.cn/",desc:""},
  {name:"学生工作指导委员会",cat:"职能部门",type:"website",url:"http://sac.sjtu.edu.cn/",desc:""},
  {name:"研究生院",cat:"职能部门",type:"website",url:"https://www.gs.sjtu.edu.cn/",desc:"研究生培养与管理"},
  {name:"国家卓越工程师学院",cat:"职能部门",type:"website",url:"https://ngcee.sjtu.edu.cn/",desc:""},
  {name:"教务处",cat:"职能部门",type:"website",url:"https://www.jwc.sjtu.edu.cn/",desc:"本科教学管理"},
  {name:"招生办公室",cat:"职能部门",type:"website",url:"https://admissions.sjtu.edu.cn/",desc:"本科招生"},
  {name:"科学技术发展研究院",cat:"职能部门",type:"website",url:"https://keyan.sjtu.edu.cn/",desc:"科研项目与成果管理"},
  {name:"先进产业技术研究院",cat:"职能部门",type:"website",url:"http://aitri.sjtu.edu.cn/",desc:""},
  {name:"地方研究院管理处",cat:"职能部门",type:"website",url:"https://rri.sjtu.edu.cn/",desc:""},
  {name:"文科建设处",cat:"职能部门",type:"website",url:"http://wk.sjtu.edu.cn/",desc:"人文社科科研管理"},
  {name:"国际合作与交流处",cat:"职能部门",type:"website",url:"http://global.sjtu.edu.cn/",desc:"外事与国际交流"},
  {name:"人力资源处",cat:"职能部门",type:"website",url:"http://hr.sjtu.edu.cn/",desc:"人事管理与招聘"},
  {name:"财务计划处",cat:"职能部门",type:"website",url:"http://www.jdcw.sjtu.edu.cn/",desc:"财务与缴费"},
  {name:"规划发展处",cat:"职能部门",type:"website",url:"https://plan.sjtu.edu.cn/",desc:""},
  {name:"重点建设办公室",cat:"职能部门",type:"website",url:"https://zdjs.sjtu.edu.cn/",desc:""},
  {name:"审计处",cat:"职能部门",type:"website",url:"http://sjchu.sjtu.edu.cn/",desc:""},
  {name:"资产管理与实验室处",cat:"职能部门",type:"website",url:"https://zcc.sjtu.edu.cn/",desc:""},
  {name:"保卫处",cat:"职能部门",type:"website",url:"http://bwc.sjtu.edu.cn/",desc:"校园安全"},
  {name:"基建处",cat:"职能部门",type:"website",url:"https://jjc.sjtu.edu.cn/",desc:"校园建设"},
  {name:"招投标与政府采购办公室",cat:"职能部门",type:"website",url:"https://pboffice.sjtu.edu.cn/",desc:""},
  {name:"校园管理办公室",cat:"职能部门",type:"website",url:"http://xygl.sjtu.edu.cn/",desc:""},
  {name:"档案文博管理中心",cat:"职能部门",type:"website",url:"http://archives.sjtu.edu.cn/",desc:""},
  {name:"教育技术中心",cat:"职能部门",type:"website",url:"http://etc.sjtu.edu.cn/",desc:""},
  {name:"学生创新中心",cat:"职能部门",type:"website",url:"https://www.si.sjtu.edu.cn/",desc:""},
  {name:"教学发展中心",cat:"职能部门",type:"website",url:"http://ctld.sjtu.edu.cn/",desc:""},
  {name:"终身教育学院",cat:"职能部门",type:"website",url:"https://lec.sjtu.edu.cn/",desc:"继续教育与非学历教育"},
  {name:"后勤保障中心",cat:"职能部门",type:"website",url:"http://houqin.sjtu.edu.cn/",desc:"住宿、餐饮与校园服务"},

  // 招生、就业与国际教育
  {name:"本科招生网",cat:"招生就业",type:"website",url:"https://admissions.sjtu.edu.cn/",desc:"本科招生政策与咨询"},
  {name:"研究生招生网",cat:"招生就业",type:"website",url:"https://yzb.sjtu.edu.cn/",desc:"硕士、博士招生"},
  {name:"学生就业服务和职业发展中心",cat:"招生就业",type:"website",url:"https://www.job.sjtu.edu.cn/",desc:"就业信息与招聘活动"},
  {name:"留学交大",cat:"招生就业",type:"website",url:"https://global.sjtu.edu.cn/en/study-sjtu/prospective",desc:"国际学生招生与学习"},
  {name:"人才招聘",cat:"招生就业",type:"website",url:"http://join.sjtu.edu.cn/",desc:"学校教职岗位"},

  // 理工科院系
  {name:"船舶海洋与建筑工程学院",cat:"学院·理工科",type:"website",url:"http://naoce.sjtu.edu.cn/",desc:""},
  {name:"机械与动力工程学院",cat:"学院·理工科",type:"website",url:"http://me.sjtu.edu.cn/",desc:""},
  {name:"电子信息与电气工程学院",cat:"学院·理工科",type:"website",url:"http://www.seiee.sjtu.edu.cn/",desc:"SEIEE"},
  {name:"电气工程学院",cat:"学院·理工科",type:"website",url:"https://see.sjtu.edu.cn/",desc:""},
  {name:"自动化与感知学院",cat:"学院·理工科",type:"website",url:"https://sais.sjtu.edu.cn/",desc:"SAIS"},
  {name:"计算机学院（网络空间安全学院、密码学院）",cat:"学院·理工科",type:"website",url:"https://www.cs.sjtu.edu.cn/",desc:""},
  {name:"集成电路学院（信息与电子工程学院）",cat:"学院·理工科",type:"website",url:"https://icisee.sjtu.edu.cn/",desc:""},
  {name:"材料科学与工程学院",cat:"学院·理工科",type:"website",url:"http://smse.sjtu.edu.cn/",desc:""},
  {name:"环境科学与工程学院",cat:"学院·理工科",type:"website",url:"http://sese.sjtu.edu.cn/",desc:""},
  {name:"生物医学工程学院",cat:"学院·理工科",type:"website",url:"http://bme.sjtu.edu.cn/",desc:""},
  {name:"航空航天学院",cat:"学院·理工科",type:"website",url:"http://www.aero.sjtu.edu.cn/",desc:""},
  {name:"化学化工学院",cat:"学院·理工科",type:"website",url:"http://scce.sjtu.edu.cn/",desc:""},
  {name:"海洋学院",cat:"学院·理工科",type:"website",url:"http://soo.sjtu.edu.cn/",desc:""},
  {name:"人工智能学院",cat:"学院·理工科",type:"website",url:"https://soai.sjtu.edu.cn/",desc:""},
  {name:"数学科学学院",cat:"学院·理工科",type:"website",url:"http://www.math.sjtu.edu.cn/",desc:""},
  {name:"物理与天文学院",cat:"学院·理工科",type:"website",url:"http://www.physics.sjtu.edu.cn/",desc:""},
  {name:"生命科学技术学院",cat:"学院·理工科",type:"website",url:"http://life.sjtu.edu.cn/",desc:""},
  {name:"农业与生物学院",cat:"学院·理工科",type:"website",url:"http://www.agri.sjtu.edu.cn/",desc:""},
  {name:"药学院",cat:"学院·理工科",type:"website",url:"http://pharm.sjtu.edu.cn/",desc:""},
  {name:"心理学院",cat:"学院·理工科",type:"website",url:"https://psychology.sjtu.edu.cn/",desc:""},

  // 人文社科、商科与设计
  {name:"安泰经济与管理学院",cat:"学院·人文商科",type:"website",url:"http://www.acem.sjtu.edu.cn/",desc:"ACEM"},
  {name:"凯原法学院",cat:"学院·人文商科",type:"website",url:"http://law.sjtu.edu.cn/",desc:""},
  {name:"外国语学院",cat:"学院·人文商科",type:"website",url:"http://sfl.sjtu.edu.cn/",desc:""},
  {name:"人文学院",cat:"学院·人文商科",type:"website",url:"http://shss.sjtu.edu.cn/",desc:""},
  {name:"马克思主义学院",cat:"学院·人文商科",type:"website",url:"https://ma.sjtu.edu.cn/",desc:""},
  {name:"国际与公共事务学院",cat:"学院·人文商科",type:"website",url:"http://www.sipa.sjtu.edu.cn/",desc:""},
  {name:"媒体与传播学院",cat:"学院·人文商科",type:"website",url:"https://smc.sjtu.edu.cn/",desc:""},
  {name:"设计学院",cat:"学院·人文商科",type:"website",url:"https://designschool.sjtu.edu.cn/",desc:""},
  {name:"体育系",cat:"学院·人文商科",type:"website",url:"http://tiyuxi.sjtu.edu.cn/",desc:""},
  {name:"上海高级金融学院",cat:"学院·人文商科",type:"website",url:"http://www.saif.sjtu.edu.cn/",desc:"SAIF"},
  {name:"中欧国际工商学院",cat:"学院·人文商科",type:"website",url:"https://www.ceibs.edu/",desc:"CEIBS"},

  // 特色学院
  {name:"浦江国际学院（原密西根学院）",cat:"特色学院",type:"website",url:"https://www.ji.sjtu.edu.cn/",desc:"校级官网现用名称"},
  {name:"巴黎卓越工程师学院",cat:"特色学院",type:"website",url:"http://speit.sjtu.edu.cn/",desc:"SPEIT"},
  {name:"上海交大-南加州大学文化创意产业学院",cat:"特色学院",type:"website",url:"https://icci.sjtu.edu.cn/",desc:"ICCI"},
  {name:"中英国际低碳学院",cat:"特色学院",type:"website",url:"http://lcc.sjtu.edu.cn/",desc:""},
  {name:"致远学院",cat:"特色学院",type:"website",url:"http://zhiyuan.sjtu.edu.cn/",desc:""},
  {name:"教育学院",cat:"特色学院",type:"website",url:"https://soe.sjtu.edu.cn/",desc:""},
  {name:"智慧能源创新学院",cat:"特色学院",type:"website",url:"http://www.senergy.sjtu.edu.cn/",desc:""},
  {name:"溥渊未来技术学院",cat:"特色学院",type:"website",url:"https://gift.sjtu.edu.cn/",desc:""},

  // 医学院系
  {name:"上海交通大学医学院",cat:"学院·医科",type:"website",url:"https://www.shsmu.edu.cn/",desc:"医学院总站"},
  {name:"医学院教务处",cat:"学院·医科",type:"website",url:"https://www.shsmu.edu.cn/jwc/",desc:"医学教育教学"},

  // 主要研究院与科研机构
  {name:"系统生物医学研究院",cat:"研究院所",type:"website",url:"https://scsb.sjtu.edu.cn/",desc:""},
  {name:"自然科学研究院",cat:"研究院所",type:"website",url:"https://ins.sjtu.edu.cn/",desc:""},
  {name:"李政道研究所",cat:"研究院所",type:"website",url:"https://tdli.sjtu.edu.cn/",desc:""},
  {name:"中国法与社会研究院",cat:"研究院所",type:"website",url:"http://www.socio-legal.sjtu.edu.cn/",desc:""},
  {name:"变革性分子前沿科学中心",cat:"研究院所",type:"website",url:"https://fsctm.sjtu.edu.cn/",desc:""},
  {name:"张江高等研究院",cat:"研究院所",type:"website",url:"https://zias.sjtu.edu.cn/",desc:""},
  {name:"能源研究院",cat:"研究院所",type:"website",url:"http://energy.sjtu.edu.cn/",desc:""},
  {name:"医疗机器人研究院",cat:"研究院所",type:"website",url:"https://imr.sjtu.edu.cn/",desc:""},
  {name:"人工智能研究院",cat:"研究院所",type:"website",url:"http://ai.sjtu.edu.cn/",desc:""},
  {name:"元知机器人研究院",cat:"研究院所",type:"website",url:"https://mri.sjtu.edu.cn/",desc:""},
  {name:"Bio-X 研究院",cat:"研究院所",type:"website",url:"https://bio-x.sjtu.edu.cn/",desc:""},
  {name:"转化医学研究院",cat:"研究院所",type:"website",url:"https://transmed.sjtu.edu.cn/#/",desc:""},
  {name:"董浩云智能管理与物流研究院",cat:"研究院所",type:"website",url:"http://www.sugli.sjtu.edu.cn/",desc:""},
  {name:"新农村发展研究院",cat:"研究院所",type:"website",url:"http://www.inrd.sjtu.edu.cn/",desc:""},
  {name:"碳中和发展研究院",cat:"研究院所",type:"website",url:"https://ricn.sjtu.edu.cn/",desc:""},
  {name:"区域国别研究院",cat:"研究院所",type:"website",url:"https://airs.sjtu.edu.cn/",desc:""},
  {name:"智能传播研究院",cat:"研究院所",type:"website",url:"https://ici.sjtu.edu.cn/",desc:""},
  {name:"主动健康战略与发展研究院",cat:"研究院所",type:"website",url:"https://iph.sjtu.edu.cn/",desc:""},
  {name:"深远海科学与工程研究院",cat:"研究院所",type:"website",url:"https://most.sjtu.edu.cn/",desc:""},

  // 附属医院
  {name:"瑞金医院",cat:"附属医院",type:"website",url:"http://www.rjh.com.cn/",desc:"上海交大医学院附属"},
  {name:"仁济医院",cat:"附属医院",type:"website",url:"https://www.renji.com/",desc:"上海交大医学院附属"},
  {name:"新华医院",cat:"附属医院",type:"website",url:"http://www.xinhuamed.com.cn/",desc:"上海交大医学院附属"},
  {name:"第九人民医院",cat:"附属医院",type:"website",url:"http://www.9hospital.com.cn/",desc:"上海交大医学院附属"},
  {name:"上海市第一人民医院",cat:"附属医院",type:"website",url:"http://www.firsthospital.cn/home/index.html",desc:"上海交大医学院附属"},
  {name:"上海市第六人民医院",cat:"附属医院",type:"website",url:"http://www.6thhosp.com/",desc:"上海交大医学院附属"},
  {name:"上海儿童医学中心",cat:"附属医院",type:"website",url:"https://www.scmc.com.cn/",desc:"上海交大医学院附属"},
  {name:"上海市儿童医院",cat:"附属医院",type:"website",url:"http://www.shchildren.com.cn/",desc:"上海交大医学院附属"},
  {name:"上海市胸科医院",cat:"附属医院",type:"website",url:"http://www.shxkyy.com/",desc:"上海交大医学院附属"},
  {name:"上海市精神卫生中心",cat:"附属医院",type:"website",url:"https://www.smhc.org.cn/",desc:"上海交大医学院附属"},
  {name:"同仁医院",cat:"附属医院",type:"website",url:"https://www.shtrhospital.com/index.aspx",desc:"上海交大医学院附属"},

  // 校园文化、校友与基金会
  {name:"校团委",cat:"学生组织与文化",type:"website",url:"https://youth.sjtu.edu.cn/",desc:"共青团上海交通大学委员会"},
  {name:"视觉交大",cat:"学生组织与文化",type:"website",url:"https://vs.sjtu.edu.cn/",desc:"校园影像"},
  {name:"钱学森图书馆",cat:"学生组织与文化",type:"website",url:"http://www.qianxslib.sjtu.edu.cn/",desc:""},
  {name:"李政道图书馆",cat:"学生组织与文化",type:"website",url:"https://tdllib.sjtu.edu.cn/",desc:""},
  {name:"交大博物馆",cat:"学生组织与文化",type:"website",url:"https://archives.sjtu.edu.cn/wbcg/jdbwg.htm",desc:""},
  {name:"校友总会",cat:"校友与基金会",type:"website",url:"https://alumni.sjtu.edu.cn/",desc:""},
  {name:"教育发展基金会",cat:"校友与基金会",type:"website",url:"https://foundation.sjtu.edu.cn/",desc:"公益捐赠与奖助学金"},

  // 微信公众号：只保留能从校方或单位公开页确认的搜索名称
  {name:"上海交通大学",cat:"综合门户",type:"wechat",desc:"学校官方微信"},
  {name:"上交大",cat:"招生就业",type:"wechat",desc:"本科招生官方微信"},
  {name:"上交大研招",cat:"招生就业",type:"wechat",desc:"研究生招生官方微信"},
  {name:"上海交通大学教务处",cat:"职能部门",type:"wechat",desc:"教务处官方微信平台"},
  {name:"上海交大研究生院",cat:"职能部门",type:"wechat",desc:"研究生院官方微信"},
  {name:"平安交大",cat:"职能部门",type:"wechat",desc:"交大保卫处"},
  {name:"交大就业",cat:"招生就业",type:"wechat",desc:"学生就业服务和职业发展中心"},
  {name:"上海交通大学图书馆",cat:"综合门户",type:"wechat",desc:"图书馆官方微信"},
  {name:"益友sjtu",cat:"学生组织与文化",type:"wechat",desc:"校团委官方微信"},
  {name:"上海交大生活",cat:"学生组织与文化",type:"wechat",desc:"后勤服务信息查询"},
  {name:"上海交通大学学生创新中心",cat:"职能部门",type:"wechat",desc:"上海交通大学学生创新中心"},
  {name:"交大思思",cat:"学生组织与文化",type:"wechat",desc:"社会实践信息查询"},
  {name:"上海交通大学学生联合会",cat:"学生组织与文化",type:"wechat",desc:"学生联合会官方微信"},
  {name:"交大团委zzb",cat:"职能部门",type:"wechat",desc:"上海交通大学校团委组织部"},
  {name:"交大家园",cat:"学生组织与文化",type:"wechat",desc:"交大学生社区风采"},
  {name:"上海交通大学学生事务中心",cat:"职能部门",type:"wechat",desc:"上海交通大学学生事务中心"},
  {name:"交大就业",cat:"招生就业",type:"wechat",desc:"上海交通大学学生就业服务和职业发展中心"},
  {name:"交我算",cat:"综合门户",type:"wechat",desc:"上海交大计算平台"},
  {name:"SJTU勤工助学部",cat:"学生组织与文化",type:"wechat",desc:"勤工助学信息"},
  {name:"上海交通大学学生体育总会",cat:"学生组织与文化",type:"wechat",desc:"上海交通大学学生体育总会"},
  {name:"333的招协人",cat:"招生就业",type:"wechat",desc:"上海交通大学招生宣传志愿者协会"},
  {name:"交大思思",cat:"学生组织与文化",type:"wechat",desc:"社会实践信息查询"},
];
