window.JIAOWODAO_CLUB_META = { ratingUpdatedAt: "2025-12-18", contactUpdatedAt: "2025-07-02", count: 150 };

window.JIAOWODAO_CLUB_DATA = [
  {
    "name": "歌手联盟",
    "name_en": "歌手联盟",
    "type": "club",
    "cat": "五星社团",
    "cat_en": "Five-star Clubs",
    "rating": 5,
    "websiteUrl": null,
    "wechatName": "交大歌手联盟",
    "qqGroups": [
      "1139417533",
      "829664675"
    ],
    "qqNote": null
  },
  {
    "name": "书画篆刻协会",
    "name_en": "书画篆刻协会",
    "type": "club",
    "cat": "五星社团",
    "cat_en": "Five-star Clubs",
    "rating": 5,
    "websiteUrl": null,
    "wechatName": "交大书协",
    "qqGroups": [
      "758178496"
    ],
    "qqNote": null
  },
  {
    "name": "阳光剧社",
    "name_en": "阳光剧社",
    "type": "club",
    "cat": "五星社团",
    "cat_en": "Five-star Clubs",
    "rating": 5,
    "websiteUrl": null,
    "wechatName": "阳光剧社",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "数字山海社",
    "name_en": "数字山海社",
    "type": "club",
    "cat": "五星社团",
    "cat_en": "Five-star Clubs",
    "rating": 5,
    "websiteUrl": null,
    "wechatName": null,
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "525街舞协会",
    "name_en": "525街舞协会",
    "type": "club",
    "cat": "五星社团",
    "cat_en": "Five-star Clubs",
    "rating": 5,
    "websiteUrl": null,
    "wechatName": "525dancecrewSJTU",
    "qqGroups": [
      "945078332"
    ],
    "qqNote": null
  },
  {
    "name": "国学社",
    "name_en": "国学社",
    "type": "club",
    "cat": "五星社团",
    "cat_en": "Five-star Clubs",
    "rating": 5,
    "websiteUrl": "https://sjtuguoxue.space/",
    "wechatName": "上海交大国学社",
    "qqGroups": [
      "709881123"
    ],
    "qqNote": null
  },
  {
    "name": "极限飞盘协会",
    "name_en": "极限飞盘协会",
    "type": "club",
    "cat": "五星社团",
    "cat_en": "Five-star Clubs",
    "rating": 5,
    "websiteUrl": null,
    "wechatName": "交大极限飞盘",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "器乐交流协会",
    "name_en": "器乐交流协会",
    "type": "club",
    "cat": "五星社团",
    "cat_en": "Five-star Clubs",
    "rating": 5,
    "websiteUrl": null,
    "wechatName": null,
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "玛纳卡实验剧社",
    "name_en": "玛纳卡实验剧社",
    "type": "club",
    "cat": "五星社团",
    "cat_en": "Five-star Clubs",
    "rating": 5,
    "websiteUrl": null,
    "wechatName": "玛纳卡实验剧社",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "Minecraft社",
    "name_en": "Minecraft社",
    "type": "club",
    "cat": "五星社团",
    "cat_en": "Five-star Clubs",
    "rating": 5,
    "websiteUrl": "https://mc.sjtu.cn/welcome/",
    "wechatName": "上海交通大学Minecraft社",
    "qqGroups": [],
    "qqNote": "关注公众号可见"
  },
  {
    "name": "魔术协会",
    "name_en": "魔术协会",
    "type": "club",
    "cat": "四星社团",
    "cat_en": "Four-star Clubs",
    "rating": 4,
    "websiteUrl": null,
    "wechatName": null,
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "阿卡贝拉清唱社",
    "name_en": "阿卡贝拉清唱社",
    "type": "club",
    "cat": "四星社团",
    "cat_en": "Four-star Clubs",
    "rating": 4,
    "websiteUrl": null,
    "wechatName": "SJTU阿卡贝拉",
    "qqGroups": [
      "735449603"
    ],
    "qqNote": null
  },
  {
    "name": "吉他协会",
    "name_en": "吉他协会",
    "type": "club",
    "cat": "四星社团",
    "cat_en": "Four-star Clubs",
    "rating": 4,
    "websiteUrl": null,
    "wechatName": "交大吉协",
    "qqGroups": [
      "678290975"
    ],
    "qqNote": null
  },
  {
    "name": "科幻奇幻协会",
    "name_en": "科幻奇幻协会",
    "type": "club",
    "cat": "四星社团",
    "cat_en": "Four-star Clubs",
    "rating": 4,
    "websiteUrl": "https://gpabooks.github.io/",
    "wechatName": "交大幻协",
    "qqGroups": [],
    "qqNote": "关注公众号可见"
  },
  {
    "name": "SJTU创新创业协会",
    "name_en": "SJTU创新创业协会",
    "type": "club",
    "cat": "四星社团",
    "cat_en": "Four-star Clubs",
    "rating": 4,
    "websiteUrl": null,
    "wechatName": "SJTU双创",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "上海交通大学红十字会",
    "name_en": "上海交通大学红十字会",
    "type": "club",
    "cat": "四星社团",
    "cat_en": "Four-star Clubs",
    "rating": 4,
    "websiteUrl": null,
    "wechatName": null,
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "乐队联盟",
    "name_en": "乐队联盟",
    "type": "club",
    "cat": "四星社团",
    "cat_en": "Four-star Clubs",
    "rating": 4,
    "websiteUrl": "http://phonicavi.com/sjtu/rock_sjtu/wiki/about.html",
    "wechatName": "交大乐队联盟",
    "qqGroups": [
      "467732302"
    ],
    "qqNote": null
  },
  {
    "name": "晨曦志愿者服务社",
    "name_en": "晨曦志愿者服务社",
    "type": "club",
    "cat": "四星社团",
    "cat_en": "Four-star Clubs",
    "rating": 4,
    "websiteUrl": null,
    "wechatName": "晨曦志愿服务社",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "跑虫俱乐部",
    "name_en": "跑虫俱乐部",
    "type": "club",
    "cat": "四星社团",
    "cat_en": "Four-star Clubs",
    "rating": 4,
    "websiteUrl": null,
    "wechatName": "SJTU跑虫俱乐部",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "龙舟协会",
    "name_en": "龙舟协会",
    "type": "club",
    "cat": "四星社团",
    "cat_en": "Four-star Clubs",
    "rating": 4,
    "websiteUrl": null,
    "wechatName": null,
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "交大学生全球胜任力发展协会",
    "name_en": "交大学生全球胜任力发展协会",
    "type": "club",
    "cat": "四星社团",
    "cat_en": "Four-star Clubs",
    "rating": 4,
    "websiteUrl": null,
    "wechatName": "上海交大学生全球胜任力发展协会",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "头脑奥林匹克社团",
    "name_en": "头脑奥林匹克社团",
    "type": "club",
    "cat": "四星社团",
    "cat_en": "Four-star Clubs",
    "rating": 4,
    "websiteUrl": null,
    "wechatName": null,
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "Fsquare舞蹈协会",
    "name_en": "Fsquare舞蹈协会",
    "type": "club",
    "cat": "四星社团",
    "cat_en": "Four-star Clubs",
    "rating": 4,
    "websiteUrl": null,
    "wechatName": "Fsquare舞社",
    "qqGroups": [
      "1130329805"
    ],
    "qqNote": null
  },
  {
    "name": "笛箫协会",
    "name_en": "笛箫协会",
    "type": "club",
    "cat": "四星社团",
    "cat_en": "Four-star Clubs",
    "rating": 4,
    "websiteUrl": null,
    "wechatName": "上交笛协",
    "qqGroups": [
      "820576040"
    ],
    "qqNote": null
  },
  {
    "name": "音乐剧社",
    "name_en": "音乐剧社",
    "type": "club",
    "cat": "四星社团",
    "cat_en": "Four-star Clubs",
    "rating": 4,
    "websiteUrl": null,
    "wechatName": "SJTU音乐剧社",
    "qqGroups": [
      "910696019"
    ],
    "qqNote": null
  },
  {
    "name": "台球协会",
    "name_en": "台球协会",
    "type": "club",
    "cat": "三星社团",
    "cat_en": "Three-star Clubs",
    "rating": 3,
    "websiteUrl": null,
    "wechatName": "SJTU台协",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "跆拳道协会",
    "name_en": "跆拳道协会",
    "type": "club",
    "cat": "三星社团",
    "cat_en": "Three-star Clubs",
    "rating": 3,
    "websiteUrl": null,
    "wechatName": "SJTU跆拳道协会",
    "qqGroups": [
      "705666865"
    ],
    "qqNote": null
  },
  {
    "name": "高尔夫协会",
    "name_en": "高尔夫协会",
    "type": "club",
    "cat": "三星社团",
    "cat_en": "Three-star Clubs",
    "rating": 3,
    "websiteUrl": null,
    "wechatName": null,
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "上海交通大学冰壶协会",
    "name_en": "上海交通大学冰壶协会",
    "type": "club",
    "cat": "三星社团",
    "cat_en": "Three-star Clubs",
    "rating": 3,
    "websiteUrl": null,
    "wechatName": "sjtu_curling",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "足球协会",
    "name_en": "足球协会",
    "type": "club",
    "cat": "三星社团",
    "cat_en": "Three-star Clubs",
    "rating": 3,
    "websiteUrl": null,
    "wechatName": "上海交大足协",
    "qqGroups": [
      "287734388",
      "891079284"
    ],
    "qqNote": null
  },
  {
    "name": "野外生存协会",
    "name_en": "野外生存协会",
    "type": "club",
    "cat": "三星社团",
    "cat_en": "Three-star Clubs",
    "rating": 3,
    "websiteUrl": "https://www.sjtuoutdoor.com/",
    "wechatName": "交大野协",
    "qqGroups": [
      "939840382"
    ],
    "qqNote": null
  },
  {
    "name": "南洋舞社",
    "name_en": "南洋舞社",
    "type": "club",
    "cat": "三星社团",
    "cat_en": "Three-star Clubs",
    "rating": 3,
    "websiteUrl": null,
    "wechatName": "南洋舞社",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "滑雪协会",
    "name_en": "滑雪协会",
    "type": "club",
    "cat": "三星社团",
    "cat_en": "Three-star Clubs",
    "rating": 3,
    "websiteUrl": null,
    "wechatName": "SJTUSKI",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "钢琴协会",
    "name_en": "钢琴协会",
    "type": "club",
    "cat": "三星社团",
    "cat_en": "Three-star Clubs",
    "rating": 3,
    "websiteUrl": null,
    "wechatName": "sjtu钢协",
    "qqGroups": [
      "532062808",
      "876010598"
    ],
    "qqNote": null
  },
  {
    "name": "鹭缘观鸟社",
    "name_en": "鹭缘观鸟社",
    "type": "club",
    "cat": "三星社团",
    "cat_en": "Three-star Clubs",
    "rating": 3,
    "websiteUrl": null,
    "wechatName": "东川鹭缘",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "JOY交有喜剧",
    "name_en": "JOY交有喜剧",
    "type": "club",
    "cat": "三星社团",
    "cat_en": "Three-star Clubs",
    "rating": 3,
    "websiteUrl": null,
    "wechatName": null,
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "围棋协会",
    "name_en": "围棋协会",
    "type": "club",
    "cat": "三星社团",
    "cat_en": "Three-star Clubs",
    "rating": 3,
    "websiteUrl": null,
    "wechatName": "交大围棋",
    "qqGroups": [
      "329450018"
    ],
    "qqNote": null
  },
  {
    "name": "上海交大电子竞技协会",
    "name_en": "上海交大电子竞技协会",
    "type": "club",
    "cat": "三星社团",
    "cat_en": "Three-star Clubs",
    "rating": 3,
    "websiteUrl": null,
    "wechatName": "上海交大电竞社",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "乒乓球协会",
    "name_en": "乒乓球协会",
    "type": "club",
    "cat": "三星社团",
    "cat_en": "Three-star Clubs",
    "rating": 3,
    "websiteUrl": null,
    "wechatName": "SJTU乒协",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "中国象棋协会",
    "name_en": "中国象棋协会",
    "type": "club",
    "cat": "三星社团",
    "cat_en": "Three-star Clubs",
    "rating": 3,
    "websiteUrl": null,
    "wechatName": "上海交大棋联、思源象协",
    "qqGroups": [
      "761011306"
    ],
    "qqNote": null
  },
  {
    "name": "篮球协会",
    "name_en": "篮球协会",
    "type": "club",
    "cat": "三星社团",
    "cat_en": "Three-star Clubs",
    "rating": 3,
    "websiteUrl": null,
    "wechatName": "交大蓝协",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "“风光无限”新能源协会",
    "name_en": "“风光无限”新能源协会",
    "type": "club",
    "cat": "三星社团",
    "cat_en": "Three-star Clubs",
    "rating": 3,
    "websiteUrl": null,
    "wechatName": null,
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "射艺协会",
    "name_en": "射艺协会",
    "type": "club",
    "cat": "三星社团",
    "cat_en": "Three-star Clubs",
    "rating": 3,
    "websiteUrl": null,
    "wechatName": "思源弓社",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "国防军事协会",
    "name_en": "国防军事协会",
    "type": "club",
    "cat": "三星社团",
    "cat_en": "Three-star Clubs",
    "rating": 3,
    "websiteUrl": null,
    "wechatName": null,
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "天文爱好者协会",
    "name_en": "天文爱好者协会",
    "type": "club",
    "cat": "三星社团",
    "cat_en": "Three-star Clubs",
    "rating": 3,
    "websiteUrl": "https://xiuyunmarx.github.io/SJTUAstronomyAssociation.github.io/",
    "wechatName": "思源星君",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "800号电影社",
    "name_en": "800号电影社",
    "type": "club",
    "cat": "三星社团",
    "cat_en": "Three-star Clubs",
    "rating": 3,
    "websiteUrl": null,
    "wechatName": "800号电影社",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "中日桥",
    "name_en": "中日桥",
    "type": "club",
    "cat": "三星社团",
    "cat_en": "Three-star Clubs",
    "rating": 3,
    "websiteUrl": null,
    "wechatName": "SJTU中日桥",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "Freedom Zone动漫协会",
    "name_en": "Freedom Zone动漫协会",
    "type": "club",
    "cat": "三星社团",
    "cat_en": "Three-star Clubs",
    "rating": 3,
    "websiteUrl": null,
    "wechatName": "浮泽",
    "qqGroups": [
      "1039892016"
    ],
    "qqNote": null
  },
  {
    "name": "网球协会",
    "name_en": "网球协会",
    "type": "club",
    "cat": "三星社团",
    "cat_en": "Three-star Clubs",
    "rating": 3,
    "websiteUrl": null,
    "wechatName": "上交网协",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "SJTUPA摄影协会",
    "name_en": "SJTUPA摄影协会",
    "type": "club",
    "cat": "三星社团",
    "cat_en": "Three-star Clubs",
    "rating": 3,
    "websiteUrl": null,
    "wechatName": "SJTUPA摄影协会",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "上海交通大学和合华韵社",
    "name_en": "上海交通大学和合华韵社",
    "type": "club",
    "cat": "三星社团",
    "cat_en": "Three-star Clubs",
    "rating": 3,
    "websiteUrl": null,
    "wechatName": null,
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "城市定向社",
    "name_en": "城市定向社",
    "type": "club",
    "cat": "三星社团",
    "cat_en": "Three-star Clubs",
    "rating": 3,
    "websiteUrl": null,
    "wechatName": null,
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "SJTU灯塔传记社",
    "name_en": "SJTU灯塔传记社",
    "type": "club",
    "cat": "三星社团",
    "cat_en": "Three-star Clubs",
    "rating": 3,
    "websiteUrl": null,
    "wechatName": null,
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "“守望”临终关怀大学生志愿者协会",
    "name_en": "“守望”临终关怀大学生志愿者协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "交大守望HospiceCare",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "“小豸援助”上海交通大学法律援助中心",
    "name_en": "“小豸援助”上海交通大学法律援助中心",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "小豸援助",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "2.5次元偶像研究学社",
    "name_en": "2.5次元偶像研究学社",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "上海交大偶像研究院",
    "qqGroups": [
      "292897098"
    ],
    "qqNote": null
  },
  {
    "name": "3D造物社",
    "name_en": "3D造物社",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "3D造物社",
    "qqGroups": [],
    "qqNote": "关注公众号可见"
  },
  {
    "name": "J-Teen说唱社",
    "name_en": "J-Teen说唱社",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "J-Teen说唱社",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "Linux用户组",
    "name_en": "Linux用户组",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": "https://sjtug.org/",
    "wechatName": "SJTUG",
    "qqGroups": [
      "715273806"
    ],
    "qqNote": null
  },
  {
    "name": "RM交龙机器人战队",
    "name_en": "RM交龙机器人战队",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "上海交大交龙机器人俱乐部",
    "qqGroups": [
      "709881123",
      "710299378"
    ],
    "qqNote": null
  },
  {
    "name": "SJTU源社",
    "name_en": "SJTU源社",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "SJTU源社",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "vision美术协会",
    "name_en": "vision美术协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "交大美协",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "爱健康（原翡翠丝带——健康知识科普学社）",
    "name_en": "爱健康（原翡翠丝带——健康知识科普学社）",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "SJTU翡翠丝带",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "安泰职业生涯发展协会",
    "name_en": "安泰职业生涯发展协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "交大安泰CDA",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "巴蜀文化交流协会",
    "name_en": "巴蜀文化交流协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "SJTU巴协",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "白岩诗社",
    "name_en": "白岩诗社",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "交大白岩诗社",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "棒垒球协会",
    "name_en": "棒垒球协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "交大棒垒",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "边界哲学社",
    "name_en": "边界哲学社",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "边界哲学社",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "搏击协会",
    "name_en": "搏击协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "上交格斗俱乐部",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "布鸽桌游社",
    "name_en": "布鸽桌游社",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "SJTU-BGA",
    "qqGroups": [
      "314980657"
    ],
    "qqNote": null
  },
  {
    "name": "船舶与海洋工程协会",
    "name_en": "船舶与海洋工程协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": null,
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "创想社",
    "name_en": "创想社",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "上海交大ICCI创想社",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "大学生心理发展研讨会",
    "name_en": "大学生心理发展研讨会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "SJTU交心",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "电子音乐社",
    "name_en": "电子音乐社",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "SJTU电音社",
    "qqGroups": [
      "821633409"
    ],
    "qqNote": null
  },
  {
    "name": "二十四节令鼓队",
    "name_en": "二十四节令鼓队",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "SJTU二十四节令鼓队",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "馆遍上海",
    "name_en": "馆遍上海",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "sjtu馆遍上海",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "国际标准舞协会",
    "name_en": "国际标准舞协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "上海交大国际舞",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "国际象棋协会",
    "name_en": "国际象棋协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "上海交大棋协",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "国情研习社",
    "name_en": "国情研习社",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "国情研习社",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "海洋协会",
    "name_en": "海洋协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "SJTUOceanAssociation",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "航运与物流学会",
    "name_en": "航运与物流学会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": null,
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "烘焙社",
    "name_en": "烘焙社",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "SJTU烘焙社",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "幻圆互动媒体创作社",
    "name_en": "幻圆互动媒体创作社",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "MagicCircleSJTU",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "剑道协会",
    "name_en": "剑道协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "东川路800号剑道社",
    "qqGroups": [
      "831464698"
    ],
    "qqNote": null
  },
  {
    "name": "交大行业研究与投资俱乐部",
    "name_en": "交大行业研究与投资俱乐部",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "上交投研",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "街头健身协会",
    "name_en": "街头健身协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": null,
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "截拳道协会",
    "name_en": "截拳道协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "SJTUJeetKuneDo",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "精油与芳香疗法社团",
    "name_en": "精油与芳香疗法社团",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "SJTU精油与芳香疗法社团",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "空手道协会",
    "name_en": "空手道协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "SJTU交大空手道",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "蓝海社",
    "name_en": "蓝海社",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "蓝海社",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "览卓藏文化社",
    "name_en": "览卓藏文化社",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "览卓藏文化社",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "领读者学生阅读推广社团",
    "name_en": "领读者学生阅读推广社团",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "上海交大领读者",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "轮滑社",
    "name_en": "轮滑社",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "SJTU轮滑社",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "绿格公益团",
    "name_en": "绿格公益团",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "绿格SJTU",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "绿色金融协会",
    "name_en": "绿色金融协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": null,
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "梅花桩武术协会",
    "name_en": "梅花桩武术协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": null,
    "qqGroups": [
      "367071164"
    ],
    "qqNote": null
  },
  {
    "name": "美式橄榄球社团",
    "name_en": "美式橄榄球社团",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": null,
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "模拟联合国协会",
    "name_en": "模拟联合国协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "交大模联",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "魔方协会",
    "name_en": "魔方协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "SJTU魔方社",
    "qqGroups": [
      "282891586"
    ],
    "qqNote": null
  },
  {
    "name": "南船社",
    "name_en": "南船社",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": null,
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "排球协会",
    "name_en": "排球协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "交大排协",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "葡萄与葡萄酒协会",
    "name_en": "葡萄与葡萄酒协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "SJTU葡萄与葡萄酒",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "蒲公英服务社",
    "name_en": "蒲公英服务社",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "蒲公英服务社",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "桥牌协会",
    "name_en": "桥牌协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "SJTUBridge",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "青年学习社",
    "name_en": "青年学习社",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": null,
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "区块链协会",
    "name_en": "区块链协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": "https://acm.sjtu.edu.cn/~htftsy/",
    "wechatName": "SJTUblockchain",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "拳击协会",
    "name_en": "拳击协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "上交格斗俱乐部",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "赛艇协会",
    "name_en": "赛艇协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "交大赛艇俱乐部",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "上海交通大学“习近平新时代中国特色社会主义思想”学习研讨会",
    "name_en": "上海交通大学“习近平新时代中国特色社会主义思想”学习研讨会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "交大青年集结号",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "上海交通大学滑板协会",
    "name_en": "上海交通大学滑板协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "交大滑板社",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "上海交通大学赛车队",
    "name_en": "上海交通大学赛车队",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "SJTU赛车队",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "上海交通大学投行咨询协会",
    "name_en": "上海交通大学投行咨询协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "SJTU_BAC",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "上海交通大学学生生涯发展协会",
    "name_en": "上海交通大学学生生涯发展协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "SCDU",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "上海交通大学咏春协会",
    "name_en": "上海交通大学咏春协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": null,
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "生物多样性保护协会",
    "name_en": "生物多样性保护协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": null,
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "史学社",
    "name_en": "史学社",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "史学社",
    "qqGroups": [
      "768554216"
    ],
    "qqNote": null
  },
  {
    "name": "手语协会",
    "name_en": "手语协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "sjtu手语协会",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "数学建模协会",
    "name_en": "数学建模协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "SJTU数学建模",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "思辨学社",
    "name_en": "思辨学社",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "交大辩论",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "思南汉服协会",
    "name_en": "思南汉服协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "思南汉韵",
    "qqGroups": [
      "336815777"
    ],
    "qqNote": null
  },
  {
    "name": "思源爱心服务社",
    "name_en": "思源爱心服务社",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "SJTU思源爱心服务社",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "思源卫星社团",
    "name_en": "思源卫星社团",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": null,
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "四国天下军棋社",
    "name_en": "四国天下军棋社",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": null,
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "太极协会",
    "name_en": "太极协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": null,
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "碳中和协会",
    "name_en": "碳中和协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": null,
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "铁人三项协会",
    "name_en": "铁人三项协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "SJTU铁三",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "推理协会",
    "name_en": "推理协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "上海交大推协",
    "qqGroups": [
      "949871266"
    ],
    "qqNote": null
  },
  {
    "name": "退役大学生士兵协会",
    "name_en": "退役大学生士兵协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "交大戎耀",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "万智桌游协会",
    "name_en": "万智桌游协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "交大万智桌游",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "网络文化工作室联盟",
    "name_en": "网络文化工作室联盟",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "上海交通大学网络文化工作室联盟",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "未来建筑师协会",
    "name_en": "未来建筑师协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "未建协sjtu",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "无人机俱乐部",
    "name_en": "无人机俱乐部",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "SJTU无人机俱乐部",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "西州古琴社",
    "name_en": "西州古琴社",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "上海交通大学西州古琴社",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "仙人掌与多肉植物协会",
    "name_en": "仙人掌与多肉植物协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "交大肉协",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "相声协会",
    "name_en": "相声协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "新语相声",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "小动物关爱协会",
    "name_en": "小动物关爱协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "SJTU喵汪",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "学生科技与教育交流协会",
    "name_en": "学生科技与教育交流协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "TECC",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "学生校友服务发展协会",
    "name_en": "学生校友服务发展协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": null,
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "哑巴电台",
    "name_en": "哑巴电台",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "哑巴FM",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "阳光工程志愿者协会",
    "name_en": "阳光工程志愿者协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "上海交大阳光工程",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "一九咖啡协会",
    "name_en": "一九咖啡协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "SJTU一九咖啡",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "音游社",
    "name_en": "音游社",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "SJTU音游社",
    "qqGroups": [
      "481612397"
    ],
    "qqNote": null
  },
  {
    "name": "英国皇家化工协会",
    "name_en": "英国皇家化工协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": null,
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "英语辩论社",
    "name_en": "英语辩论社",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "SJTU英语辩论社",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "羽毛球协会",
    "name_en": "羽毛球协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "交大羽协",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "豫文化交流协会",
    "name_en": "豫文化交流协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "SJTU豫文化交流协会",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "粤语协会",
    "name_en": "粤语协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "上交粤协",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "智能运载器俱乐部",
    "name_en": "智能运载器俱乐部",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "SJTU船模队",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "中法协会",
    "name_en": "中法协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "上海交通大学中法协会",
    "qqGroups": [],
    "qqNote": null
  },
  {
    "name": "自行车协会",
    "name_en": "自行车协会",
    "type": "club",
    "cat": "未获评星级",
    "cat_en": "Unrated Clubs",
    "rating": null,
    "websiteUrl": null,
    "wechatName": "SJTU cycling",
    "qqGroups": [],
    "qqNote": null
  }
].map(item => item.cat === "未获评星级"
  ? { ...item, cat: "其他社团", cat_en: "Other Clubs" }
  : item);
